services:
  create_blocked_slot:
    build:
      context: ./create_blocked_slot
    ports:
      - "${CREATE_BLOCKED_SLOTS_PORT-50001}:5000"

  get_doctor_schedule:
    build:
      context: ./get_doctor_schedule
    volumes:
      - ./get_doctor_schedule/src:/src
    ports:
      - "${GET_DOCTOR_SCHEDULE_PORT-50002}:5000"