services:
  create_blocked_slot:
    build:
      context: ./create_blocked_slot
    ports:
      - "50000:50000"


  manage_booking:
    build:
      context: ./manageBooking
    restart: on-failure
    ports:
      - "5007:5000"