_format_version: "3.0"

# dummy service
services:
- host: httpbin.org
  name: example_service
  port: 80
  protocol: http
  routes:
  - name: example_route
    paths:
    - /mock
    strip_path: true
