_format_version: "3.0"

services:
- name: create_blocked_slots
  url: http://createblockedslots:50000
  routes:
  - name: complex_blockedslots
    paths:
      - /createblockedslots

- name: blocked_slots
  url: http://blockedslots:5000
  routes:
  - name: view_blockedslots
    methods:
      - GET
    paths:
      - /blockedslots/view
  - name: create_blockedslots
    methods:
      - POST
    paths:
      - /blockedslots/edit

- name: clinic
  url: http://clinic:5000
  routes:
  - name: view_clinic
    methods:
      - GET
    paths:
      - /clinic/view
  - name: create_clinic
    methods:
      - POST
    paths:
      - /clinic/new
  - name: edit_clinic
    methods:
      - PUT
    paths:
      - /clinic/edit

- name: patient_profile
  url: http://profile:5000/patients
  routes:
  - name: view_patient
    methods:
      - GET
    paths:
      - /profile/patient/view
  - name: edit_patient
    methods:
      - PUT
    paths:
      - /profile/patient/edit
  - name: create_patient
    methods:
      - POST
    paths:
      - /profile/patient/new

- name: doctors_profile
  url: http://profile:5000/doctors
  routes:
  - name: view_doc
    methods:
      - GET
    paths:
      - /profile/doctor/view
  - name: create_doc
    methods:
      - POST
    paths:
      - /profile/doctor/new


- name: clinic_rating
  url: http://rating:5000/clinics
  routes:
  - name: view_rating_clinic
    methods:
      - GET
    paths:
      - /rating/clinic
  - name: create_rating_clinic
    methods:
      - POST
    paths:
      - /rating/clinic/new

- name: doctor_rating
  url: http://rating:5000/doctors
  routes:
  - name: view_rating_doc
    methods:
      - GET
    paths:
      - /rating/doctor
  - name: create_rating_doc
    methods:
      - POST
    paths:
      - /rating/doctor/new

- name: booking
  url: http://booking:5000
  routes:
  - name: view_booking
    methods:
      - GET
    paths:
      - /booking/view
  - name: edit_booking
    methods:
      - PUT
    paths:
      - /booking/edit
  - name: create_booking
    methods:
      - POST
    paths:
      - /booking/new
  - name: delete_booking
    methods:
      - DELETE
    paths:
      - /booking/delete



# global plugins
plugins:

- name: cors
  config:
    origins:
    - "*"
    methods:
    - GET
    - POST
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600

- name: rate-limiting
  config:
    second: 10
    hour: 10000
    policy: local

