global:
  scrape_interval:     10s # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules by default

scrape_configs:
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
