include:
  # - ./kong/compose.yml
  - ./ampq/compose.yml
  - ./complex/compose.yml

services:
  blocked_slots:
    build:
      context: ./simple/blocked_slots
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/blocked_slots/src:/src
    environment:
      DB_URI: ${BLOCKED_SLOTS_DB_URI}
      PORT: 5000
    ports:
      - "${BLOCKED_SLOTS_PORT-5001}:5000"

  clinic:
    build:
      context: ./simple/clinic
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/clinic/src:/src
    environment:
      DB_URI: ${CLINIC_DB_URI}
      PORT: 5000
    ports:
      - "${CLINIC_PORT-5002}:5000"

  profile:
    build:
      context: ./simple/profile
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/profile/src:/src
    environment:
      DB_URI: ${PROFILE_DB_URI}
      PORT: 5000
    ports:
      - "${PROFILE_PORT-5003}:5000"

  rating:
    build:
      context: ./simple/rating
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/rating/src:/src
    environment:
      DB_URI: ${RATING_DB_URI}
      PORT: 5000
    ports:
      - "${RATING_PORT-5004}:5000"

  booking:
    build:
      context: ./simple/booking
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/booking/src:/src
    environment:
      DB_URI: ${BOOKING_DB_URI}
      PORT: 5000
    ports:
      - "${BOOKING_PORT-5005}:5000"
      
  notification:
    build: 
      context: ./simple/notification
    volumes:
      - ./simple/notification/src:/src
    environment:
      PORT: 5000
    ports:
      - "${NOTIFICATION_PORT-5006}:5000"
  db:
    image: mysql
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - "3306"

volumes:
  db_data:
