services:
  profile:
    build:
      context: ./simple/profile
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/profile/src:/src
    environment:
      DB_URI: ${DB_BASE_URI}/profile
      PORT: 5000
    ports:
      - "${SCHEDULE_PORT-5001}:5000"

  db:
    image: mysql
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - "3306"

volumes:
  db_data:
