services:
  # blocked_slots:
  #   build:
  #     context: ./simple/blocked_slots
  #   depends_on:
  #     - db
  #   restart: on-failure
  #   volumes:
  #     - ./simple/blocked_slots/src:/src
  #   environment:
  #     DB_URI: ${DB_BASE_URI}/blocked_slots
  #     PORT: 5000
  #   ports:
  #     - "${BLOCKED_SLOTS_PORT-5001}:5000"
  clinic:
    build:
      context: ./simple/clinic
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./simple/clinic/src:/src
    environment:
      DB_URI: ${DB_BASE_URI}/clinic
      PORT: 5000
    ports:
      - "${CLINIC_PORT-5001}:5000"

  db:
    image: mysql
    # command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    expose:
      - "3306"

volumes:
  db_data:
